from .spell_components_route import SpellComponentsRoute
from .spell_school_route import SpellSchoolRoute
from .spell_scaling_route import SpellScalingRoute
from .spell_stats_route import SpellStatsRoute
from .spell_user_creation_route import SpellUserCreationRoute
from .spell_route import SpellRoute